/**
 * Checks the built site rather than the code that builds it.
 *
 * The deploy artifact is the actual product, and several of its parts have no
 * other coverage: dropping the CNAME write, breaking a link, or letting the
 * repository URL inside the generated images go stale all used to pass.
 *
 * Requires a browser for the image checks: npx playwright install chromium
 */
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import test from 'node:test';

import { ORIGIN, REPOSITORY, pagePath } from '../tools/build.mjs';
import { listen } from '../tools/serve.mjs';

let chromium;
try {
	({ chromium } = await import('playwright'));
} catch {
	chromium = null;
}

const dist = new URL('../dist/', import.meta.url);
const read = (name) => readFile(new URL(name, dist), 'utf8');

const LANGUAGES = (await readdir(new URL('../i18n/', import.meta.url)))
	.filter((name) => name.endsWith('.json'))
	.map((name) => name.replace('.json', ''));
const PAGES = ['index', 'verify', 'safety'];

test('the deploy artifact carries what GitHub Pages needs', async () => {
	assert.equal((await read('CNAME')).trim(), new URL(ORIGIN).host);
	assert.ok(existsSync(new URL('.nojekyll', dist)), '.nojekyll must be present');

	const robots = await read('robots.txt');
	assert.match(robots, /^User-agent: \*/m);
	assert.ok(robots.includes(`${ORIGIN}/sitemap.xml`), 'robots.txt must point at the sitemap');

	assert.ok(existsSync(new URL('licenses/NotoEmoji-OFL.txt', dist)), 'the font licence must ship');
});

test('the sitemap lists every page exactly once', async () => {
	const sitemap = await read('sitemap.xml');
	const found = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1]);
	const expected = LANGUAGES.flatMap((lang) => PAGES.map((page) => ORIGIN + pagePath(lang, page)));

	assert.deepEqual(found.slice().sort(), expected.slice().sort());
	assert.equal(new Set(found).size, found.length, 'no URL may appear twice');
});

test('every internal link in the built pages resolves', async () => {
	const site = await listen();
	try {
		const checked = new Set();
		const failures = [];

		for (const lang of LANGUAGES) {
			for (const page of PAGES) {
				const html = await read(`.${pagePath(lang, page)}index.html`);
				// Only same-origin references; external links are not ours to police.
				const references = [...html.matchAll(/(?:href|src)="(\/[^"]*)"/g)].map((m) => m[1]);
				assert.ok(references.length > 0, `${pagePath(lang, page)} has no local references`);

				for (const reference of references) {
					if (checked.has(reference)) {
						continue;
					}
					checked.add(reference);
					const response = await fetch(site.origin + reference);
					if (!response.ok) {
						failures.push(`${reference} -> ${response.status}`);
					}
				}
			}
		}

		assert.deepEqual(failures, [], `${failures.length} local references do not resolve`);
		assert.ok(checked.size > 20, `expected to check more than a handful, got ${checked.size}`);
	} finally {
		await site.stop();
	}
});

const browserAvailable =
	chromium !== null &&
	(await chromium
		.launch()
		.then((browser) => browser.close().then(() => true))
		.catch(() => false));

const options = browserAvailable
	? {}
	: { skip: 'no browser available; run: npx playwright install chromium' };

test('the committed images encode the current repository URL', options, async () => {
	// These are generated by `npm run images` and committed, so nothing rebuilds
	// them on a rename. The URL is inside the QR code, where no link checker
	// would ever see it, and it went stale twice.
	const jsqr = await readFile(
		new URL('../node_modules/jsqr/dist/jsQR.js', import.meta.url),
		'utf8',
	);
	const images = {
		'images/qr-test.png': await readFile(new URL('../images/qr-test.png', import.meta.url)),
		'site/og.png': await readFile(new URL('../site/og.png', import.meta.url)),
	};

	const browser = await chromium.launch();
	try {
		const page = await browser.newPage();
		await page.goto('about:blank');
		await page.addScriptTag({ content: jsqr });

		for (const [name, buffer] of Object.entries(images)) {
			const decoded = await page.evaluate(async (base64) => {
				const image = new Image();
				image.src = `data:image/png;base64,${base64}`;
				await image.decode();
				const canvas = document.createElement('canvas');
				canvas.width = image.width;
				canvas.height = image.height;
				const context = canvas.getContext('2d', { willReadFrequently: true });
				context.fillStyle = '#ffffff';
				context.fillRect(0, 0, canvas.width, canvas.height);
				context.drawImage(image, 0, 0);
				const pixels = context.getImageData(0, 0, canvas.width, canvas.height);
				const found = window.jsQR(pixels.data, canvas.width, canvas.height);
				return found === null ? null : found.data;
			}, buffer.toString('base64'));

			assert.equal(decoded, REPOSITORY, `${name} is stale; run npm run images`);
		}
	} finally {
		await browser.close();
	}
});
